version: 2.1

orbs:
  python: circleci/python@3.2.0

jobs:
  Publish-Documentation:
    executor: python/default
    steps:
      - checkout
      - run: |
          cat README.md > docs/index.md
      - run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          pip install mkdocs-material
          pip install "mkdocs-material[imaging]"
      - run: mkdocs gh-deploy --force
workflows:
  version: 2
  publish-updates:
    jobs:
      - Publish-Documentation
